#ifndef _ASM_X86_UNISTD_X32_H
#define _ASM_X86_UNISTD_X32_H

#ifndef __SYSCALL
#define __SYSCALL(a, b)
#endif

/*
 * This file contains the system call numbers for the x32 ABI.
 */

#define __NR_x32_base 4096

/* at least 8 syscall per cacheline */
#define __NR_x32_read				(__NR_x32_base + 0)
__SYSCALL(__NR_x32_read, sys_read)
#define __NR_x32_write				(__NR_x32_base + 1)
__SYSCALL(__NR_x32_write, sys_write)
#define __NR_x32_open				(__NR_x32_base + 2)
__SYSCALL(__NR_x32_open, compat_sys_open)
#define __NR_x32_close				(__NR_x32_base + 3)
__SYSCALL(__NR_x32_close, sys_close)
#define __NR_x32_stat				(__NR_x32_base + 4)
__SYSCALL(__NR_x32_stat, compat_sys_newstat)
#define __NR_x32_fstat				(__NR_x32_base + 5)
__SYSCALL(__NR_x32_fstat, compat_sys_newfstat)
#define __NR_x32_lstat				(__NR_x32_base + 6)
__SYSCALL(__NR_x32_lstat, compat_sys_newlstat)
#define __NR_x32_poll				(__NR_x32_base + 7)
__SYSCALL(__NR_x32_poll, sys_poll)

#define __NR_x32_lseek				(__NR_x32_base + 8)
__SYSCALL(__NR_x32_lseek, sys_lseek)
#define __NR_x32_mmap				(__NR_x32_base + 9)
__SYSCALL(__NR_x32_mmap, sys_mmap)
#define __NR_x32_mprotect			(__NR_x32_base + 10)
__SYSCALL(__NR_x32_mprotect, sys_mprotect)
#define __NR_x32_munmap				(__NR_x32_base + 11)
__SYSCALL(__NR_x32_munmap, sys_munmap)
#define __NR_x32_brk				(__NR_x32_base + 12)
__SYSCALL(__NR_x32_brk, sys_brk)
#define __NR_x32_rt_sigaction			(__NR_x32_base + 13)
__SYSCALL(__NR_x32_rt_sigaction, sys32_rt_sigaction)
#define __NR_x32_rt_sigprocmask			(__NR_x32_base + 14)
__SYSCALL(__NR_x32_rt_sigprocmask, sys32_rt_sigprocmask)
#define __NR_x32_rt_sigreturn			(__NR_x32_base + 15)
__SYSCALL(__NR_x32_rt_sigreturn, stub_x32_rt_sigreturn)

#define __NR_x32_ioctl				(__NR_x32_base + 16)
__SYSCALL(__NR_x32_ioctl, compat_sys_ioctl)
#define __NR_x32_pread64			(__NR_x32_base + 17)
__SYSCALL(__NR_x32_pread64, sys_pread64)
#define __NR_x32_pwrite64			(__NR_x32_base + 18)
__SYSCALL(__NR_x32_pwrite64, sys_pwrite64)
#define __NR_x32_readv				(__NR_x32_base + 19)
__SYSCALL(__NR_x32_readv, compat_sys_readv)
#define __NR_x32_writev				(__NR_x32_base + 20)
__SYSCALL(__NR_x32_writev, compat_sys_writev)
#define __NR_x32_access				(__NR_x32_base + 21)
__SYSCALL(__NR_x32_access, sys_access)
#define __NR_x32_pipe				(__NR_x32_base + 22)
__SYSCALL(__NR_x32_pipe, sys_pipe)
#define __NR_x32_select				(__NR_x32_base + 23)
__SYSCALL(__NR_x32_select, compat_sys_select)

#define __NR_x32_sched_yield			(__NR_x32_base + 24)
__SYSCALL(__NR_x32_sched_yield, sys_sched_yield)
#define __NR_x32_mremap				(__NR_x32_base + 25)
__SYSCALL(__NR_x32_mremap, sys_mremap)
#define __NR_x32_msync				(__NR_x32_base + 26)
__SYSCALL(__NR_x32_msync, sys_msync)
#define __NR_x32_mincore			(__NR_x32_base + 27)
__SYSCALL(__NR_x32_mincore, sys_mincore)
#define __NR_x32_madvise			(__NR_x32_base + 28)
__SYSCALL(__NR_x32_madvise, sys_madvise)
#define __NR_x32_shmget				(__NR_x32_base + 29)
__SYSCALL(__NR_x32_shmget, sys_shmget)
#define __NR_x32_shmat				(__NR_x32_base + 30)
__SYSCALL(__NR_x32_shmat, compat_sys_x32_shmat)
#define __NR_x32_shmctl				(__NR_x32_base + 31)
__SYSCALL(__NR_x32_shmctl, compat_sys_shmctl)

#define __NR_x32_dup				(__NR_x32_base + 32)
__SYSCALL(__NR_x32_dup, sys_dup)
#define __NR_x32_dup2				(__NR_x32_base + 33)
__SYSCALL(__NR_x32_dup2, sys_dup2)
#define __NR_x32_pause				(__NR_x32_base + 34)
__SYSCALL(__NR_x32_pause, sys_pause)
#define __NR_x32_nanosleep			(__NR_x32_base + 35)
__SYSCALL(__NR_x32_nanosleep, compat_sys_nanosleep)
#define __NR_x32_getitimer			(__NR_x32_base + 36)
__SYSCALL(__NR_x32_getitimer, compat_sys_getitimer)
#define __NR_x32_alarm				(__NR_x32_base + 37)
__SYSCALL(__NR_x32_alarm, sys_alarm)
#define __NR_x32_setitimer			(__NR_x32_base + 38)
__SYSCALL(__NR_x32_setitimer, compat_sys_setitimer)
#define __NR_x32_getpid				(__NR_x32_base + 39)
__SYSCALL(__NR_x32_getpid, sys_getpid)

#define __NR_x32_sendfile			(__NR_x32_base + 40)
__SYSCALL(__NR_x32_sendfile, sys_sendfile64)
#define __NR_x32_socket				(__NR_x32_base + 41)
__SYSCALL(__NR_x32_socket, sys_socket)
#define __NR_x32_connect			(__NR_x32_base + 42)
__SYSCALL(__NR_x32_connect, sys_connect)
#define __NR_x32_accept				(__NR_x32_base + 43)
__SYSCALL(__NR_x32_accept, sys_accept)
#define __NR_x32_sendto				(__NR_x32_base + 44)
__SYSCALL(__NR_x32_sendto, sys_sendto)
#define __NR_x32_recvfrom			(__NR_x32_base + 45)
__SYSCALL(__NR_x32_recvfrom, compat_sys_recvfrom)
#define __NR_x32_sendmsg			(__NR_x32_base + 46)
__SYSCALL(__NR_x32_sendmsg, compat_sys_sendmsg)
#define __NR_x32_recvmsg			(__NR_x32_base + 47)
__SYSCALL(__NR_x32_recvmsg, compat_sys_recvmsg)

#define __NR_x32_shutdown			(__NR_x32_base + 48)
__SYSCALL(__NR_x32_shutdown, sys_shutdown)
#define __NR_x32_bind				(__NR_x32_base + 49)
__SYSCALL(__NR_x32_bind, sys_bind)
#define __NR_x32_listen				(__NR_x32_base + 50)
__SYSCALL(__NR_x32_listen, sys_listen)
#define __NR_x32_getsockname			(__NR_x32_base + 51)
__SYSCALL(__NR_x32_getsockname, sys_getsockname)
#define __NR_x32_getpeername			(__NR_x32_base + 52)
__SYSCALL(__NR_x32_getpeername, sys_getpeername)
#define __NR_x32_socketpair			(__NR_x32_base + 53)
__SYSCALL(__NR_x32_socketpair, sys_socketpair)
#define __NR_x32_setsockopt			(__NR_x32_base + 54)
__SYSCALL(__NR_x32_setsockopt, compat_sys_setsockopt)
#define __NR_x32_getsockopt			(__NR_x32_base + 55)
__SYSCALL(__NR_x32_getsockopt, compat_sys_getsockopt)

#define __NR_x32_clone				(__NR_x32_base + 56)
__SYSCALL(__NR_x32_clone, stub_clone)
#define __NR_x32_fork				(__NR_x32_base + 57)
__SYSCALL(__NR_x32_fork, stub_fork)
#define __NR_x32_vfork				(__NR_x32_base + 58)
__SYSCALL(__NR_x32_vfork, stub_vfork)
#define __NR_x32_execve				(__NR_x32_base + 59)
__SYSCALL(__NR_x32_execve, stub_x32_execve)
#define __NR_x32_exit				(__NR_x32_base + 60)
__SYSCALL(__NR_x32_exit, sys_exit)
#define __NR_x32_wait4				(__NR_x32_base + 61)
__SYSCALL(__NR_x32_wait4, compat_sys_wait4)
#define __NR_x32_kill				(__NR_x32_base + 62)
__SYSCALL(__NR_x32_kill, sys_kill)
#define __NR_x32_uname				(__NR_x32_base + 63)
__SYSCALL(__NR_x32_uname, sys_newuname)

#define __NR_x32_semget				(__NR_x32_base + 64)
__SYSCALL(__NR_x32_semget, sys_semget)
#define __NR_x32_semop				(__NR_x32_base + 65)
__SYSCALL(__NR_x32_semop, sys_semop)
#define __NR_x32_semctl				(__NR_x32_base + 66)
__SYSCALL(__NR_x32_semctl, compat_sys_x32_semctl)
#define __NR_x32_shmdt				(__NR_x32_base + 67)
__SYSCALL(__NR_x32_shmdt, sys_shmdt)
#define __NR_x32_msgget				(__NR_x32_base + 68)
__SYSCALL(__NR_x32_msgget, sys_msgget)
#define __NR_x32_msgsnd				(__NR_x32_base + 69)
__SYSCALL(__NR_x32_msgsnd, compat_sys_x32_msgsnd)
#define __NR_x32_msgrcv				(__NR_x32_base + 70)
__SYSCALL(__NR_x32_msgrcv, compat_sys_x32_msgrcv)
#define __NR_x32_msgctl				(__NR_x32_base + 71)
__SYSCALL(__NR_x32_msgctl, compat_sys_msgctl)

#define __NR_x32_fcntl				(__NR_x32_base + 72)
__SYSCALL(__NR_x32_fcntl, compat_sys_fcntl64)
#define __NR_x32_flock				(__NR_x32_base + 73)
__SYSCALL(__NR_x32_flock, sys_flock)
#define __NR_x32_fsync				(__NR_x32_base + 74)
__SYSCALL(__NR_x32_fsync, sys_fsync)
#define __NR_x32_fdatasync			(__NR_x32_base + 75)
__SYSCALL(__NR_x32_fdatasync, sys_fdatasync)
#define __NR_x32_truncate			(__NR_x32_base + 76)
__SYSCALL(__NR_x32_truncate, sys_truncate)
#define __NR_x32_ftruncate			(__NR_x32_base + 77)
__SYSCALL(__NR_x32_ftruncate, sys_ftruncate)
#define __NR_x32_getdents			(__NR_x32_base + 78)
__SYSCALL(__NR_x32_getdents, compat_sys_getdents)
#define __NR_x32_getcwd				(__NR_x32_base + 79)
__SYSCALL(__NR_x32_getcwd, sys_getcwd)

#define __NR_x32_chdir				(__NR_x32_base + 80)
__SYSCALL(__NR_x32_chdir, sys_chdir)
#define __NR_x32_fchdir				(__NR_x32_base + 81)
__SYSCALL(__NR_x32_fchdir, sys_fchdir)
#define __NR_x32_rename				(__NR_x32_base + 82)
__SYSCALL(__NR_x32_rename, sys_rename)
#define __NR_x32_mkdir				(__NR_x32_base + 83)
__SYSCALL(__NR_x32_mkdir, sys_mkdir)
#define __NR_x32_rmdir				(__NR_x32_base + 84)
__SYSCALL(__NR_x32_rmdir, sys_rmdir)
#define __NR_x32_creat				(__NR_x32_base + 85)
__SYSCALL(__NR_x32_creat, sys_creat)
#define __NR_x32_link				(__NR_x32_base + 86)
__SYSCALL(__NR_x32_link, sys_link)
#define __NR_x32_unlink				(__NR_x32_base + 87)
__SYSCALL(__NR_x32_unlink, sys_unlink)

#define __NR_x32_symlink			(__NR_x32_base + 88)
__SYSCALL(__NR_x32_symlink, sys_symlink)
#define __NR_x32_readlink			(__NR_x32_base + 89)
__SYSCALL(__NR_x32_readlink, sys_readlink)
#define __NR_x32_chmod				(__NR_x32_base + 90)
__SYSCALL(__NR_x32_chmod, sys_chmod)
#define __NR_x32_fchmod				(__NR_x32_base + 91)
__SYSCALL(__NR_x32_fchmod, sys_fchmod)
#define __NR_x32_chown				(__NR_x32_base + 92)
__SYSCALL(__NR_x32_chown, sys_chown)
#define __NR_x32_fchown				(__NR_x32_base + 93)
__SYSCALL(__NR_x32_fchown, sys_fchown)
#define __NR_x32_lchown				(__NR_x32_base + 94)
__SYSCALL(__NR_x32_lchown, sys_lchown)
#define __NR_x32_umask				(__NR_x32_base + 95)
__SYSCALL(__NR_x32_umask, sys_umask)

#define __NR_x32_gettimeofday			(__NR_x32_base + 96)
__SYSCALL(__NR_x32_gettimeofday, compat_sys_gettimeofday)
#define __NR_x32_getrlimit			(__NR_x32_base + 97)
__SYSCALL(__NR_x32_getrlimit, compat_sys_getrlimit)
#define __NR_x32_getrusage			(__NR_x32_base + 98)
__SYSCALL(__NR_x32_getrusage, compat_sys_getrusage)
#define __NR_x32_sysinfo			(__NR_x32_base + 99)
__SYSCALL(__NR_x32_sysinfo, compat_sys_sysinfo)
#define __NR_x32_times				(__NR_x32_base + 100)
__SYSCALL(__NR_x32_times, compat_sys_times)
#define __NR_x32_ptrace				(__NR_x32_base + 101)
__SYSCALL(__NR_x32_ptrace, sys_ptrace)
#define __NR_x32_getuid				(__NR_x32_base + 102)
__SYSCALL(__NR_x32_getuid, sys_getuid)
#define __NR_x32_syslog				(__NR_x32_base + 103)
__SYSCALL(__NR_x32_syslog, sys_syslog)

/* at the very end the stuff that never runs during the benchmarks */
#define __NR_x32_getgid				(__NR_x32_base + 104)
__SYSCALL(__NR_x32_getgid, sys_getgid)
#define __NR_x32_setuid				(__NR_x32_base + 105)
__SYSCALL(__NR_x32_setuid, sys_setuid)
#define __NR_x32_setgid				(__NR_x32_base + 106)
__SYSCALL(__NR_x32_setgid, sys_setgid)
#define __NR_x32_geteuid			(__NR_x32_base + 107)
__SYSCALL(__NR_x32_geteuid, sys_geteuid)
#define __NR_x32_getegid			(__NR_x32_base + 108)
__SYSCALL(__NR_x32_getegid, sys_getegid)
#define __NR_x32_setpgid			(__NR_x32_base + 109)
__SYSCALL(__NR_x32_setpgid, sys_setpgid)
#define __NR_x32_getppid			(__NR_x32_base + 110)
__SYSCALL(__NR_x32_getppid, sys_getppid)
#define __NR_x32_getpgrp			(__NR_x32_base + 111)
__SYSCALL(__NR_x32_getpgrp, sys_getpgrp)

#define __NR_x32_setsid				(__NR_x32_base + 112)
__SYSCALL(__NR_x32_setsid, sys_setsid)
#define __NR_x32_setreuid			(__NR_x32_base + 113)
__SYSCALL(__NR_x32_setreuid, sys_setreuid)
#define __NR_x32_setregid			(__NR_x32_base + 114)
__SYSCALL(__NR_x32_setregid, sys_setregid)
#define __NR_x32_getgroups			(__NR_x32_base + 115)
__SYSCALL(__NR_x32_getgroups, sys_getgroups)
#define __NR_x32_setgroups			(__NR_x32_base + 116)
__SYSCALL(__NR_x32_setgroups, sys_setgroups)
#define __NR_x32_setresuid			(__NR_x32_base + 117)
__SYSCALL(__NR_x32_setresuid, sys_setresuid)
#define __NR_x32_getresuid			(__NR_x32_base + 118)
__SYSCALL(__NR_x32_getresuid, sys_getresuid)
#define __NR_x32_setresgid			(__NR_x32_base + 119)
__SYSCALL(__NR_x32_setresgid, sys_setresgid)

#define __NR_x32_getresgid			(__NR_x32_base + 120)
__SYSCALL(__NR_x32_getresgid, sys_getresgid)
#define __NR_x32_getpgid			(__NR_x32_base + 121)
__SYSCALL(__NR_x32_getpgid, sys_getpgid)
#define __NR_x32_setfsuid			(__NR_x32_base + 122)
__SYSCALL(__NR_x32_setfsuid, sys_setfsuid)
#define __NR_x32_setfsgid			(__NR_x32_base + 123)
__SYSCALL(__NR_x32_setfsgid, sys_setfsgid)
#define __NR_x32_getsid				(__NR_x32_base + 124)
__SYSCALL(__NR_x32_getsid, sys_getsid)
#define __NR_x32_capget				(__NR_x32_base + 125)
__SYSCALL(__NR_x32_capget, sys_capget)
#define __NR_x32_capset				(__NR_x32_base + 126)
__SYSCALL(__NR_x32_capset, sys_capset)

#define __NR_x32_rt_sigpending			(__NR_x32_base + 127)
__SYSCALL(__NR_x32_rt_sigpending, sys32_rt_sigpending)
#define __NR_x32_rt_sigtimedwait		(__NR_x32_base + 128)
__SYSCALL(__NR_x32_rt_sigtimedwait, compat_sys_rt_sigtimedwait)
#define __NR_x32_rt_sigqueueinfo		(__NR_x32_base + 129)
__SYSCALL(__NR_x32_rt_sigqueueinfo, sys32_rt_sigqueueinfo)
#define __NR_x32_rt_sigsuspend			(__NR_x32_base + 130)
__SYSCALL(__NR_x32_rt_sigsuspend, sys_rt_sigsuspend)
#define __NR_x32_sigaltstack			(__NR_x32_base + 131)
__SYSCALL(__NR_x32_sigaltstack, stub_x32_sigaltstack)
#define __NR_x32_utime				(__NR_x32_base + 132)
__SYSCALL(__NR_x32_utime, compat_sys_utime)
#define __NR_x32_mknod				(__NR_x32_base + 133)
__SYSCALL(__NR_x32_mknod, sys_mknod)

/* Only needed for a.out */
#define __NR_x32_uselib				(__NR_x32_base + 134)
__SYSCALL(__NR_x32_uselib, sys_ni_syscall)
#define __NR_x32_personality			(__NR_x32_base + 135)
__SYSCALL(__NR_x32_personality, sys_personality)

#define __NR_x32_ustat				(__NR_x32_base + 136)
__SYSCALL(__NR_x32_ustat, compat_sys_ustat)
#define __NR_x32_statfs				(__NR_x32_base + 137)
__SYSCALL(__NR_x32_statfs, compat_sys_statfs)
#define __NR_x32_fstatfs			(__NR_x32_base + 138)
__SYSCALL(__NR_x32_fstatfs, compat_sys_fstatfs)
#define __NR_x32_sysfs				(__NR_x32_base + 139)
__SYSCALL(__NR_x32_sysfs, sys_sysfs)

#define __NR_x32_getpriority			(__NR_x32_base + 140)
__SYSCALL(__NR_x32_getpriority, sys_getpriority)
#define __NR_x32_setpriority			(__NR_x32_base + 141)
__SYSCALL(__NR_x32_setpriority, sys_setpriority)
#define __NR_x32_sched_setparam			(__NR_x32_base + 142)
__SYSCALL(__NR_x32_sched_setparam, sys_sched_setparam)
#define __NR_x32_sched_getparam			(__NR_x32_base + 143)
__SYSCALL(__NR_x32_sched_getparam, sys_sched_getparam)
#define __NR_x32_sched_setscheduler		(__NR_x32_base + 144)
__SYSCALL(__NR_x32_sched_setscheduler, sys_sched_setscheduler)
#define __NR_x32_sched_getscheduler		(__NR_x32_base + 145)
__SYSCALL(__NR_x32_sched_getscheduler, sys_sched_getscheduler)
#define __NR_x32_sched_get_priority_max		(__NR_x32_base + 146)
__SYSCALL(__NR_x32_sched_get_priority_max, sys_sched_get_priority_max)
#define __NR_x32_sched_get_priority_min		(__NR_x32_base + 147)
__SYSCALL(__NR_x32_sched_get_priority_min, sys_sched_get_priority_min)
#define __NR_x32_sched_rr_get_interval		(__NR_x32_base + 148)
__SYSCALL(__NR_x32_sched_rr_get_interval, sys32_sched_rr_get_interval)

#define __NR_x32_mlock				(__NR_x32_base + 149)
__SYSCALL(__NR_x32_mlock, sys_mlock)
#define __NR_x32_munlock			(__NR_x32_base + 150)
__SYSCALL(__NR_x32_munlock, sys_munlock)
#define __NR_x32_mlockall			(__NR_x32_base + 151)
__SYSCALL(__NR_x32_mlockall, sys_mlockall)
#define __NR_x32_munlockall			(__NR_x32_base + 152)
__SYSCALL(__NR_x32_munlockall, sys_munlockall)

#define __NR_x32_vhangup			(__NR_x32_base + 153)
__SYSCALL(__NR_x32_vhangup, sys_vhangup)

#define __NR_x32_modify_ldt			(__NR_x32_base + 154)
__SYSCALL(__NR_x32_modify_ldt, sys_modify_ldt)

#define __NR_x32_pivot_root			(__NR_x32_base + 155)
__SYSCALL(__NR_x32_pivot_root, sys_pivot_root)

#define __NR_x32__sysctl			(__NR_x32_base + 156)
__SYSCALL(__NR_x32__sysctl, compat_sys_sysctl)

#define __NR_x32_prctl				(__NR_x32_base + 157)
__SYSCALL(__NR_x32_prctl, sys_prctl)
#define __NR_x32_arch_prctl			(__NR_x32_base + 158)
__SYSCALL(__NR_x32_arch_prctl, sys_arch_prctl)

#define __NR_x32_adjtimex			(__NR_x32_base + 159)
__SYSCALL(__NR_x32_adjtimex, compat_sys_adjtimex)

#define __NR_x32_setrlimit			(__NR_x32_base + 160)
__SYSCALL(__NR_x32_setrlimit, compat_sys_setrlimit)

#define __NR_x32_chroot				(__NR_x32_base + 161)
__SYSCALL(__NR_x32_chroot, sys_chroot)

#define __NR_x32_sync				(__NR_x32_base + 162)
__SYSCALL(__NR_x32_sync, sys_sync)

#define __NR_x32_acct				(__NR_x32_base + 163)
__SYSCALL(__NR_x32_acct, sys_acct)

#define __NR_x32_settimeofday			(__NR_x32_base + 164)
__SYSCALL(__NR_x32_settimeofday, compat_sys_settimeofday)

#define __NR_x32_mount				(__NR_x32_base + 165)
__SYSCALL(__NR_x32_mount, sys_mount)
#define __NR_x32_umount2			(__NR_x32_base + 166)
__SYSCALL(__NR_x32_umount2, sys_umount)

#define __NR_x32_swapon				(__NR_x32_base + 167)
__SYSCALL(__NR_x32_swapon, sys_swapon)
#define __NR_x32_swapoff			(__NR_x32_base + 168)
__SYSCALL(__NR_x32_swapoff, sys_swapoff)

#define __NR_x32_reboot				(__NR_x32_base + 169)
__SYSCALL(__NR_x32_reboot, sys_reboot)

#define __NR_x32_sethostname			(__NR_x32_base + 170)
__SYSCALL(__NR_x32_sethostname, sys_sethostname)
#define __NR_x32_setdomainname			(__NR_x32_base + 171)
__SYSCALL(__NR_x32_setdomainname, sys_setdomainname)

#define __NR_x32_iopl				(__NR_x32_base + 172)
__SYSCALL(__NR_x32_iopl, stub_iopl)
#define __NR_x32_ioperm				(__NR_x32_base + 173)
__SYSCALL(__NR_x32_ioperm, sys_ioperm)

#define __NR_x32_create_module			(__NR_x32_base + 174)
__SYSCALL(__NR_x32_create_module, sys_ni_syscall)
#define __NR_x32_init_module			(__NR_x32_base + 175)
__SYSCALL(__NR_x32_init_module, sys_init_module)
#define __NR_x32_delete_module			(__NR_x32_base + 176)
__SYSCALL(__NR_x32_delete_module, sys_delete_module)
#define __NR_x32_get_kernel_syms		(__NR_x32_base + 177)
__SYSCALL(__NR_x32_get_kernel_syms, sys_ni_syscall)
#define __NR_x32_query_module			(__NR_x32_base + 178)
__SYSCALL(__NR_x32_query_module, sys_ni_syscall)

#define __NR_x32_quotactl			(__NR_x32_base + 179)
__SYSCALL(__NR_x32_quotactl, sys32_quotactl)

#define __NR_x32_nfsservctl			(__NR_x32_base + 180)
__SYSCALL(__NR_x32_nfsservctl, compat_sys_nfsservctl)

/* reserved for LiS/STREAMS */
#define __NR_x32_getpmsg			(__NR_x32_base + 181)
__SYSCALL(__NR_x32_getpmsg, sys_ni_syscall)
#define __NR_x32_putpmsg			(__NR_x32_base + 182)
__SYSCALL(__NR_x32_putpmsg, sys_ni_syscall)

/* reserved for AFS */
#define __NR_x32_afs_syscall			(__NR_x32_base + 183)
__SYSCALL(__NR_x32_afs_syscall, sys_ni_syscall)

/* reserved for tux */
#define __NR_x32_tuxcall			(__NR_x32_base + 184)
__SYSCALL(__NR_x32_tuxcall, sys_ni_syscall)

#define __NR_x32_security			(__NR_x32_base + 185)
__SYSCALL(__NR_x32_security, sys_ni_syscall)

#define __NR_x32_gettid				(__NR_x32_base + 186)
__SYSCALL(__NR_x32_gettid, sys_gettid)

#define __NR_x32_readahead			(__NR_x32_base + 187)
__SYSCALL(__NR_x32_readahead, sys_readahead)
#define __NR_x32_setxattr			(__NR_x32_base + 188)
__SYSCALL(__NR_x32_setxattr, sys_setxattr)
#define __NR_x32_lsetxattr			(__NR_x32_base + 189)
__SYSCALL(__NR_x32_lsetxattr, sys_lsetxattr)
#define __NR_x32_fsetxattr			(__NR_x32_base + 190)
__SYSCALL(__NR_x32_fsetxattr, sys_fsetxattr)
#define __NR_x32_getxattr			(__NR_x32_base + 191)
__SYSCALL(__NR_x32_getxattr, sys_getxattr)
#define __NR_x32_lgetxattr			(__NR_x32_base + 192)
__SYSCALL(__NR_x32_lgetxattr, sys_lgetxattr)
#define __NR_x32_fgetxattr			(__NR_x32_base + 193)
__SYSCALL(__NR_x32_fgetxattr, sys_fgetxattr)
#define __NR_x32_listxattr			(__NR_x32_base + 194)
__SYSCALL(__NR_x32_listxattr, sys_listxattr)
#define __NR_x32_llistxattr			(__NR_x32_base + 195)
__SYSCALL(__NR_x32_llistxattr, sys_llistxattr)
#define __NR_x32_flistxattr			(__NR_x32_base + 196)
__SYSCALL(__NR_x32_flistxattr, sys_flistxattr)
#define __NR_x32_removexattr			(__NR_x32_base + 197)
__SYSCALL(__NR_x32_removexattr, sys_removexattr)
#define __NR_x32_lremovexattr			(__NR_x32_base + 198)
__SYSCALL(__NR_x32_lremovexattr, sys_lremovexattr)
#define __NR_x32_fremovexattr			(__NR_x32_base + 199)
__SYSCALL(__NR_x32_fremovexattr, sys_fremovexattr)
#define __NR_x32_tkill				(__NR_x32_base + 200)
__SYSCALL(__NR_x32_tkill, sys_tkill)
#define __NR_x32_time				(__NR_x32_base + 201)
__SYSCALL(__NR_x32_time, compat_sys_time)
#define __NR_x32_futex				(__NR_x32_base + 202)
__SYSCALL(__NR_x32_futex, compat_sys_futex)
#define __NR_x32_sched_setaffinity		(__NR_x32_base + 203)
__SYSCALL(__NR_x32_sched_setaffinity, compat_sys_sched_setaffinity)
#define __NR_x32_sched_getaffinity		(__NR_x32_base + 204)
__SYSCALL(__NR_x32_sched_getaffinity, compat_sys_sched_getaffinity)
#define __NR_x32_set_thread_area		(__NR_x32_base + 205)
__SYSCALL(__NR_x32_set_thread_area, sys_set_thread_area)
#define __NR_x32_io_setup			(__NR_x32_base + 206)
__SYSCALL(__NR_x32_io_setup, compat_sys_io_setup)
#define __NR_x32_io_destroy			(__NR_x32_base + 207)
__SYSCALL(__NR_x32_io_destroy, sys_io_destroy)
#define __NR_x32_io_getevents			(__NR_x32_base + 208)
__SYSCALL(__NR_x32_io_getevents, compat_sys_io_getevents)
#define __NR_x32_io_submit			(__NR_x32_base + 209)
__SYSCALL(__NR_x32_io_submit, compat_sys_io_submit)
#define __NR_x32_io_cancel			(__NR_x32_base + 210)
__SYSCALL(__NR_x32_io_cancel, sys_io_cancel)
#define __NR_x32_get_thread_area		(__NR_x32_base + 211)
__SYSCALL(__NR_x32_get_thread_area, sys_get_thread_area)
#define __NR_x32_lookup_dcookie			(__NR_x32_base + 212)
__SYSCALL(__NR_x32_lookup_dcookie, sys_lookup_dcookie)
#define __NR_x32_epoll_create			(__NR_x32_base + 213)
__SYSCALL(__NR_x32_epoll_create, sys_epoll_create)
#define __NR_x32_epoll_ctl_old			(__NR_x32_base + 214)
__SYSCALL(__NR_x32_epoll_ctl_old, sys_ni_syscall)
#define __NR_x32_epoll_wait_old			(__NR_x32_base + 215)
__SYSCALL(__NR_x32_epoll_wait_old, sys_ni_syscall)
#define __NR_x32_remap_file_pages		(__NR_x32_base + 216)
__SYSCALL(__NR_x32_remap_file_pages, sys_remap_file_pages)
#define __NR_x32_getdents64			(__NR_x32_base + 217)
__SYSCALL(__NR_x32_getdents64, compat_sys_getdents64)
#define __NR_x32_set_tid_address		(__NR_x32_base + 218)
__SYSCALL(__NR_x32_set_tid_address, sys_set_tid_address)
#define __NR_x32_restart_syscall		(__NR_x32_base + 219)
__SYSCALL(__NR_x32_restart_syscall, sys_restart_syscall)
#define __NR_x32_semtimedop			(__NR_x32_base + 220)
__SYSCALL(__NR_x32_semtimedop, compat_sys_semtimedop)
#define __NR_x32_fadvise64			(__NR_x32_base + 221)
__SYSCALL(__NR_x32_fadvise64, sys_fadvise64)
#define __NR_x32_timer_create			(__NR_x32_base + 222)
__SYSCALL(__NR_x32_timer_create, compat_sys_timer_create)
#define __NR_x32_timer_settime			(__NR_x32_base + 223)
__SYSCALL(__NR_x32_timer_settime, compat_sys_timer_settime)
#define __NR_x32_timer_gettime			(__NR_x32_base + 224)
__SYSCALL(__NR_x32_timer_gettime, compat_sys_timer_gettime)
#define __NR_x32_timer_getoverrun		(__NR_x32_base + 225)
__SYSCALL(__NR_x32_timer_getoverrun, sys_timer_getoverrun)
#define __NR_x32_timer_delete			(__NR_x32_base + 226)
__SYSCALL(__NR_x32_timer_delete, sys_timer_delete)
#define __NR_x32_clock_settime			(__NR_x32_base + 227)
__SYSCALL(__NR_x32_clock_settime, compat_sys_clock_settime)
#define __NR_x32_clock_gettime			(__NR_x32_base + 228)
__SYSCALL(__NR_x32_clock_gettime, compat_sys_clock_gettime)
#define __NR_x32_clock_getres			(__NR_x32_base + 229)
__SYSCALL(__NR_x32_clock_getres, compat_sys_clock_getres)
#define __NR_x32_clock_nanosleep		(__NR_x32_base + 230)
__SYSCALL(__NR_x32_clock_nanosleep, compat_sys_clock_nanosleep)
#define __NR_x32_exit_group			(__NR_x32_base + 231)
__SYSCALL(__NR_x32_exit_group, sys_exit_group)
#define __NR_x32_epoll_wait			(__NR_x32_base + 232)
__SYSCALL(__NR_x32_epoll_wait, sys_epoll_wait)
#define __NR_x32_epoll_ctl			(__NR_x32_base + 233)
__SYSCALL(__NR_x32_epoll_ctl, sys_epoll_ctl)
#define __NR_x32_tgkill				(__NR_x32_base + 234)
__SYSCALL(__NR_x32_tgkill, sys_tgkill)
#define __NR_x32_utimes				(__NR_x32_base + 235)
__SYSCALL(__NR_x32_utimes, compat_sys_utimes)
#define __NR_x32_vserver			(__NR_x32_base + 236)
__SYSCALL(__NR_x32_vserver, sys_ni_syscall)
#define __NR_x32_mbind				(__NR_x32_base + 237)
__SYSCALL(__NR_x32_mbind, sys_mbind)
#define __NR_x32_set_mempolicy			(__NR_x32_base + 238)
__SYSCALL(__NR_x32_set_mempolicy, sys_set_mempolicy)
#define __NR_x32_get_mempolicy			(__NR_x32_base + 239)
__SYSCALL(__NR_x32_get_mempolicy, sys_get_mempolicy)
#define __NR_x32_mq_open			(__NR_x32_base + 240)
__SYSCALL(__NR_x32_mq_open, compat_sys_mq_open)
#define __NR_x32_mq_unlink			(__NR_x32_base + 241)
__SYSCALL(__NR_x32_mq_unlink, sys_mq_unlink)
#define __NR_x32_mq_timedsend			(__NR_x32_base + 242)
__SYSCALL(__NR_x32_mq_timedsend, compat_sys_mq_timedsend)
#define __NR_x32_mq_timedreceive		(__NR_x32_base + 243)
__SYSCALL(__NR_x32_mq_timedreceive, compat_sys_mq_timedreceive)
#define __NR_x32_mq_notify			(__NR_x32_base + 244)
__SYSCALL(__NR_x32_mq_notify, compat_sys_mq_notify)
#define __NR_x32_mq_getsetattr			(__NR_x32_base + 245)
__SYSCALL(__NR_x32_mq_getsetattr, compat_sys_mq_getsetattr)
#define __NR_x32_kexec_load			(__NR_x32_base + 246)
__SYSCALL(__NR_x32_kexec_load, compat_sys_kexec_load)
#define __NR_x32_waitid				(__NR_x32_base + 247)
__SYSCALL(__NR_x32_waitid, compat_sys_waitid)
#define __NR_x32_add_key			(__NR_x32_base + 248)
__SYSCALL(__NR_x32_add_key, sys_add_key)
#define __NR_x32_request_key			(__NR_x32_base + 249)
__SYSCALL(__NR_x32_request_key, sys_request_key)
#define __NR_x32_keyctl				(__NR_x32_base + 250)
__SYSCALL(__NR_x32_keyctl, sys_keyctl)
#define __NR_x32_ioprio_set			(__NR_x32_base + 251)
__SYSCALL(__NR_x32_ioprio_set, sys_ioprio_set)
#define __NR_x32_ioprio_get			(__NR_x32_base + 252)
__SYSCALL(__NR_x32_ioprio_get, sys_ioprio_get)
#define __NR_x32_inotify_init			(__NR_x32_base + 253)
__SYSCALL(__NR_x32_inotify_init, sys_inotify_init)
#define __NR_x32_inotify_add_watch		(__NR_x32_base + 254)
__SYSCALL(__NR_x32_inotify_add_watch, sys_inotify_add_watch)
#define __NR_x32_inotify_rm_watch		(__NR_x32_base + 255)
__SYSCALL(__NR_x32_inotify_rm_watch, sys_inotify_rm_watch)
#define __NR_x32_migrate_pages			(__NR_x32_base + 256)
__SYSCALL(__NR_x32_migrate_pages, sys_migrate_pages)
#define __NR_x32_openat				(__NR_x32_base + 257)
__SYSCALL(__NR_x32_openat, compat_sys_openat)
#define __NR_x32_mkdirat			(__NR_x32_base + 258)
__SYSCALL(__NR_x32_mkdirat, sys_mkdirat)
#define __NR_x32_mknodat			(__NR_x32_base + 259)
__SYSCALL(__NR_x32_mknodat, sys_mknodat)
#define __NR_x32_fchownat			(__NR_x32_base + 260)
__SYSCALL(__NR_x32_fchownat, sys_fchownat)
#define __NR_x32_futimesat			(__NR_x32_base + 261)
__SYSCALL(__NR_x32_futimesat, compat_sys_futimesat)
#define __NR_x32_fstatat64			(__NR_x32_base + 262)
__SYSCALL(__NR_x32_fstatat64, sys32_fstatat)
#define __NR_x32_unlinkat			(__NR_x32_base + 263)
__SYSCALL(__NR_x32_unlinkat, sys_unlinkat)
#define __NR_x32_renameat			(__NR_x32_base + 264)
__SYSCALL(__NR_x32_renameat, sys_renameat)
#define __NR_x32_linkat				(__NR_x32_base + 265)
__SYSCALL(__NR_x32_linkat, sys_linkat)
#define __NR_x32_symlinkat			(__NR_x32_base + 266)
__SYSCALL(__NR_x32_symlinkat, sys_symlinkat)
#define __NR_x32_readlinkat			(__NR_x32_base + 267)
__SYSCALL(__NR_x32_readlinkat, sys_readlinkat)
#define __NR_x32_fchmodat			(__NR_x32_base + 268)
__SYSCALL(__NR_x32_fchmodat, sys_fchmodat)
#define __NR_x32_faccessat			(__NR_x32_base + 269)
__SYSCALL(__NR_x32_faccessat, sys_faccessat)
#define __NR_x32_pselect6			(__NR_x32_base + 270)
__SYSCALL(__NR_x32_pselect6, compat_sys_pselect6)
#define __NR_x32_ppoll				(__NR_x32_base + 271)
__SYSCALL(__NR_x32_ppoll,	compat_sys_ppoll)
#define __NR_x32_unshare			(__NR_x32_base + 272)
__SYSCALL(__NR_x32_unshare,	sys_unshare)
#define __NR_x32_set_robust_list		(__NR_x32_base + 273)
__SYSCALL(__NR_x32_set_robust_list, compat_sys_set_robust_list)
#define __NR_x32_get_robust_list		(__NR_x32_base + 274)
__SYSCALL(__NR_x32_get_robust_list, compat_sys_get_robust_list)
#define __NR_x32_splice				(__NR_x32_base + 275)
__SYSCALL(__NR_x32_splice, sys_splice)
#define __NR_x32_tee				(__NR_x32_base + 276)
__SYSCALL(__NR_x32_tee, sys_tee)
#define __NR_x32_sync_file_range		(__NR_x32_base + 277)
__SYSCALL(__NR_x32_sync_file_range, sys_sync_file_range)
#define __NR_x32_vmsplice			(__NR_x32_base + 278)
__SYSCALL(__NR_x32_vmsplice, compat_sys_vmsplice)
#define __NR_x32_move_pages			(__NR_x32_base + 279)
__SYSCALL(__NR_x32_move_pages, compat_sys_move_pages)
#define __NR_x32_utimensat			(__NR_x32_base + 280)
__SYSCALL(__NR_x32_utimensat, compat_sys_utimensat)
#define __IGNORE_getcpu		/* implemented as a vsyscall */
#define __NR_x32_epoll_pwait			(__NR_x32_base + 281)
__SYSCALL(__NR_x32_epoll_pwait, sys_epoll_pwait)
#define __NR_x32_signalfd			(__NR_x32_base + 282)
__SYSCALL(__NR_x32_signalfd, compat_sys_signalfd)
#define __NR_x32_timerfd_create			(__NR_x32_base + 283)
__SYSCALL(__NR_x32_timerfd_create, sys_timerfd_create)
#define __NR_x32_eventfd			(__NR_x32_base + 284)
__SYSCALL(__NR_x32_eventfd, sys_eventfd)
#define __NR_x32_fallocate			(__NR_x32_base + 285)
__SYSCALL(__NR_x32_fallocate, sys_fallocate)
#define __NR_x32_timerfd_settime		(__NR_x32_base + 286)
__SYSCALL(__NR_x32_timerfd_settime, compat_sys_timerfd_settime)
#define __NR_x32_timerfd_gettime		(__NR_x32_base + 287)
__SYSCALL(__NR_x32_timerfd_gettime, compat_sys_timerfd_gettime)
#define __NR_x32_accept4			(__NR_x32_base + 288)
__SYSCALL(__NR_x32_accept4, sys_accept4)
#define __NR_x32_signalfd4			(__NR_x32_base + 289)
__SYSCALL(__NR_x32_signalfd4, compat_sys_signalfd4)
#define __NR_x32_eventfd2			(__NR_x32_base + 290)
__SYSCALL(__NR_x32_eventfd2, sys_eventfd2)
#define __NR_x32_epoll_create1			(__NR_x32_base + 291)
__SYSCALL(__NR_x32_epoll_create1, sys_epoll_create1)
#define __NR_x32_dup3				(__NR_x32_base + 292)
__SYSCALL(__NR_x32_dup3, sys_dup3)
#define __NR_x32_pipe2				(__NR_x32_base + 293)
__SYSCALL(__NR_x32_pipe2, sys_pipe2)
#define __NR_x32_inotify_init1			(__NR_x32_base + 294)
__SYSCALL(__NR_x32_inotify_init1, sys_inotify_init1)
#define __NR_x32_preadv				(__NR_x32_base + 295)
__SYSCALL(__NR_x32_preadv, sys_preadv)
#define __NR_x32_pwritev			(__NR_x32_base + 296)
__SYSCALL(__NR_x32_pwritev, sys_pwritev)
#define __NR_x32_rt_tgsigqueueinfo		(__NR_x32_base + 297)
__SYSCALL(__NR_x32_rt_tgsigqueueinfo, compat_sys_rt_tgsigqueueinfo)
#define __NR_x32_perf_event_open		(__NR_x32_base + 298)
__SYSCALL(__NR_x32_perf_event_open, sys_perf_event_open)
#define __NR_x32_recvmmsg			(__NR_x32_base + 299)
__SYSCALL(__NR_x32_recvmmsg, compat_sys_recvmmsg)
#define __NR_x32_fanotify_init			(__NR_x32_base + 300)
__SYSCALL(__NR_x32_fanotify_init, sys_fanotify_init)
#define __NR_x32_fanotify_mark			(__NR_x32_base + 301)
__SYSCALL(__NR_x32_fanotify_mark, sys_fanotify_mark)
#define __NR_x32_prlimit64			(__NR_x32_base + 302)
__SYSCALL(__NR_x32_prlimit64, sys_prlimit64)

/* LFS support */
#define __NR_x32_stat64				(__NR_x32_base + 303)
__SYSCALL(__NR_x32_stat64, sys32_stat64)
#define __NR_x32_fstat64			(__NR_x32_base + 304)
__SYSCALL(__NR_x32_fstat64, sys32_fstat64)
#define __NR_x32_lstat64			(__NR_x32_base + 305)
__SYSCALL(__NR_x32_lstat64, sys32_lstat64)
#define __NR_x32_statfs64			(__NR_x32_base + 306)
__SYSCALL(__NR_x32_statfs64, compat_sys_statfs64)
#define __NR_x32_fstatfs64			(__NR_x32_base + 307)
__SYSCALL(__NR_x32_fstatfs64, compat_sys_fstatfs64)

/* vDSO support */
#define __NR_x32_getcpu				(__NR_x32_base + 308)
__SYSCALL(__NR_x32_getcpu, sys_getcpu)

#endif /* _ASM_X86_UNISTD_X32_H */
