#ifndef _ASM_X86_UNISTD_64_COMPAT_H
#define _ASM_X86_UNISTD_64_COMPAT_H

#define __NR_stat			__NR_64_stat
#define __NR_fstat			__NR_64_fstat
#define __NR_lstat			__NR_64_lstat
#define __NR_rt_sigaction		__NR_64_rt_sigaction
#define __NR_rt_sigprocmask		__NR_64_rt_sigprocmask
#define __NR_rt_sigreturn		__NR_64_rt_sigreturn
#define __NR_ioctl			__NR_64_ioctl
#define __NR_readv			__NR_64_readv
#define __NR_writev			__NR_64_writev
#define __NR_select			__NR_64_select
#define __NR_shmat			__NR_64_shmat
#define __NR_shmctl			__NR_64_shmctl
#define __NR_nanosleep			__NR_64_nanosleep
#define __NR_getitimer			__NR_64_getitimer
#define __NR_setitimer			__NR_64_setitimer
#define __NR_recvfrom			__NR_64_recvfrom
#define __NR_sendmsg			__NR_64_sendmsg
#define __NR_recvmsg			__NR_64_recvmsg
#define __NR_setsockopt			__NR_64_setsockopt
#define __NR_getsockopt			__NR_64_getsockopt
#define __NR_execve			__NR_64_execve
#define __NR_wait4			__NR_64_wait4
#define __NR_semctl			__NR_64_semctl
#define __NR_msgsnd			__NR_64_msgsnd
#define __NR_msgrcv			__NR_64_msgrcv
#define __NR_msgctl			__NR_64_msgctl
#define __NR_fcntl			__NR_64_fcntl
#define __NR_getdents			__NR_64_getdents
#define __NR_gettimeofday		__NR_64_gettimeofday
#define __NR_getrlimit			__NR_64_getrlimit
#define __NR_getrusage			__NR_64_getrusage
#define __NR_sysinfo			__NR_64_sysinfo
#define __NR_times			__NR_64_times
#define __NR_rt_sigpending		__NR_64_rt_sigpending
#define __NR_rt_sigtimedwait		__NR_64_rt_sigtimedwait
#define __NR_rt_sigqueueinfo		__NR_64_rt_sigqueueinfo
#define __NR_sigaltstack		__NR_64_sigaltstack
#define __NR_utime			__NR_64_utime
#define __NR_ustat			__NR_64_ustat
#define __NR_statfs			__NR_64_statfs
#define __NR_fstatfs			__NR_64_fstatfs
#define __NR_sched_rr_get_interval	__NR_64_sched_rr_get_interval
#define __NR__sysctl			__NR_64__sysctl
#define __NR_adjtimex			__NR_64_adjtimex
#define __NR_setrlimit			__NR_64_setrlimit
#define __NR_settimeofday		__NR_64_settimeofday
#define __NR_quotactl			__NR_64_quotactl
#define __NR_nfsservctl			__NR_64_nfsservctl
#define __NR_time			__NR_64_time
#define __NR_futex			__NR_64_futex
#define __NR_sched_setaffinity		__NR_64_sched_setaffinity
#define __NR_sched_getaffinity		__NR_64_sched_getaffinity
#define __NR_io_setup			__NR_64_io_setup
#define __NR_io_getevents		__NR_64_io_getevents
#define __NR_io_submit			__NR_64_io_submit
#define __NR_getdents64			__NR_64_getdents64
#define __NR_semtimedop			__NR_64_semtimedop
#define __NR_timer_create		__NR_64_timer_create
#define __NR_timer_settime		__NR_64_timer_settime
#define __NR_timer_gettime		__NR_64_timer_gettime
#define __NR_clock_settime		__NR_64_clock_settime
#define __NR_clock_gettime		__NR_64_clock_gettime
#define __NR_clock_getres		__NR_64_clock_getres
#define __NR_clock_nanosleep		__NR_64_clock_nanosleep
#define __NR_utimes			__NR_64_utimes
#define __NR_mq_open			__NR_64_mq_open
#define __NR_mq_timedsend		__NR_64_mq_timedsend
#define __NR_mq_timedreceive		__NR_64_mq_timedreceive
#define __NR_mq_notify			__NR_64_mq_notify
#define __NR_mq_getsetattr		__NR_64_mq_getsetattr
#define __NR_kexec_load			__NR_64_kexec_load
#define __NR_waitid			__NR_64_waitid
#define __NR_openat			__NR_64_openat
#define __NR_futimesat			__NR_64_futimesat
#define __NR_newfstatat			__NR_64_newfstatat
#define __NR_pselect6			__NR_64_pselect6
#define __NR_ppoll			__NR_64_ppoll
#define __NR_set_robust_list		__NR_64_set_robust_list
#define __NR_get_robust_list		__NR_64_get_robust_list
#define __NR_vmsplice			__NR_64_vmsplice
#define __NR_move_pages			__NR_64_move_pages
#define __NR_utimensat			__NR_64_utimensat
#define __NR_signalfd			__NR_64_signalfd
#define __NR_timerfd_settime		__NR_64_timerfd_settime
#define __NR_timerfd_gettime		__NR_64_timerfd_gettime
#define __NR_signalfd4			__NR_64_signalfd4
#define __NR_rt_tgsigqueueinfo		__NR_64_rt_tgsigqueueinfo
#define __NR_recvmmsg			__NR_64_recvmmsg
#define __NR_open_by_handle_at		__NR_64_open_by_handle_at
#define __NR_clock_adjtime		__NR_64_clock_adjtime
#define __NR_sendmmsg			__NR_64_sendmmsg

#endif /* _ASM_X86_UNISTD_64_COMPAT_H */
